version: "3"
services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: utils_adm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: utils_db